FROM python:3

RUN pip3 install flask flask-restful requests numpy pronto six scipy xmltodict

COPY application.py /LayeredGraph/
COPY LayeredGraphAPI /LayeredGraph/LayeredGraphAPI/
COPY templates /LayeredGraph/templates/
COPY static /LayeredGraph/static/
RUN ls /LayeredGraph/*
WORKDIR /LayeredGraph

ENTRYPOINT ["python3", "application.py"]