FROM python:3 as builder
MAINTAINER bwilk@hudsonalpha.org

RUN pip3 install numpy scipy pronto networkx

RUN mkdir /LayeredGraph

COPY LayeredGraphAPI /LayeredGraphAPI/
COPY PubTator /PubTator/
COPY PhenotypeAPI /PhenotypeAPI/
COPY buildGraph.sh /buildGraph.sh

#RUN /buildDockerFixtures.sh
RUN /buildGraph.sh
RUN rm -rf /HPO_data_files

#look into multi-stage builds
FROM alpine
COPY --from=builder /HPO_graph_data /LayeredGraph/HPO_graph_data

VOLUME /LayeredGraph/HPO_graph_data

ENTRYPOINT ["echo", "Data only container for PyxisMap"]